server:
  port: 8080

spring:
  output:
    ansi:
      enabled: detect
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
  jpa:
    open-in-view: false
  security:
    user:
      name: dev
      password: dev

management:
  endpoints:
    web:
      exposure:
        include: "health"
  server:
    add-application-context-header: false

app:
  service-info:
    id: "org.ga4gh.serviceregistry"
    name: "GA4GH Service Registry Reference Implementation"
    type: "urn:ga4gh:serviceregistry"
    organization: "GA4GH"
    description: "Reference implementation of GA4GH Service Registry"
    documentation-url: "https://github.com/ga4gh-discovery/ga4gh-service-registry"
    contact-url:
    version: 1.0