server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  http:
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: "health"
  server:
    add-application-context-header: false
